const CACHE_EXPIRY = {
  NONE: 'NONE',
  EVERY_END_OF_DAY: 'EVERY_END_OF_DAY',
  EVERY_END_OF_WEEK: 'EVERY_END_OF_WEEK',
  EVERY_END_OF_MONTH: 'EVERY_END_OF_MONTH',
  EVERY_END_OF_YEAR: 'EVERY_END_OF_YEAR',
};

export default CACHE_EXPIRY;
