const CACHE_EXPIRY = {
  NONE: 'NONE',
  EVERY_END_OF_DAY: 'EVERY_END_OF_DAY',
  EVERY_END_OF_WEEK: 'EVERY_END_OF_WEEK',
  EVERY_END_OF_MONTH: 'EVERY_END_OF_MONTH',
  EVERY_END_OF_YEAR: 'EVERY_END_OF_YEAR',
};

const IMAGE_RESOLUTION = {
  '1x': 1,
  '2x': 2,
  '3x': 3,
};

export {CACHE_EXPIRY, IMAGE_RESOLUTION};
